<?php
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function facebook_block_info()
{
    $block['facebook_feed'] = array(
        'info' => t('Facebook feed'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    return $block;
}

function facebook_block_configure($delta = '')
{
    // This example comes from node.module.
    $form = array();
    if ($delta == 'facebook_feed') {
        $form['facebook_app_id'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook app_id'),
            '#default_value' => variable_get('facebook_app_id'),
        );
        $form['facebook_app_secret'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook app_secret'),
            '#default_value' => variable_get('facebook_app_secret'),
        );
        $form['facebook_page_id'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook page id'),
            '#default_value' => variable_get('facebook_page_id'),
        );
        $form['facebook_limit'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook limit (max 25)'),
            '#default_value' => variable_get('facebook_limit', 3),
        );
        $form['facebook_page'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook page url'),
            '#default_value' => variable_get('facebook_page'),
        );
        $form['facebook_caracteres'] = array(
            '#type' => 'textfield',
            '#title' => t('Facebook longueur des articles'),
            '#default_value' => variable_get('facebook_caracteres', 150),
        );
    }
    return $form;
}

function facebook_block_save($delta = '', $edit = array())
{
    // This example comes from node.module.
    if ($delta == 'facebook_feed') {
        variable_set('facebook_app_id', $edit['facebook_app_id']);
        variable_set('facebook_app_secret', $edit['facebook_app_secret']);
        variable_set('facebook_page_id', $edit['facebook_page_id']);
        variable_set('facebook_limit', $edit['facebook_limit']);
        variable_set('facebook_page', $edit['facebook_page']);
        variable_set('facebook_caracteres', $edit['facebook_caracteres']);
    }
}

/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function facebook_block_view($block_key)
{
    $block = array();

    if ($block_key == 'facebook_feed') { //We only want to define the content of OUR block
        //Define the block content.
        $block['content'] = _facebook_generate(json_decode(@file_get_contents('https://graph.facebook.com/v2.9/' . variable_get('facebook_page_id') . '/feed?fields=message,picture,created_time&format=json&access_token=' . variable_get('facebook_app_id') . '|' . variable_get('facebook_app_secret') . '&limit=' . variable_get('facebook_limit'))));
    }
    return $block;
}

function _facebook_generate($fb)
{
    $return = '';
    dsm($fb);
    if (isset($fb->data)) {
        $return .= '<div class="sidebar-home-twitter"><div class="panel panel-primary"><div class="panel-heading"><h6 class="panel-title with-icon"><a href="' . variable_get('facebook_page') . '" target="_blank">SUIVEZ NOUS <i>SUR FACEBOOK</i></a></h6></div><div class="panel-body scrolly scrollbar-outer">';
        foreach ($fb->data as $post) {
            @$message = mb_substr($post->message, 0, variable_get('facebook_caracteres'));
            if (@!empty($message)) {
                if (@strlen($post->message) > strlen($message)) {
                    $message .= '...';
                }
            } else {
                $message .= "Découvrez le nouvel événement mis en ligne sur notre page";
            }
            $prepic = explode("/", $post->picture);
            $jsonimg = json_decode(@file_get_contents('https://graph.facebook.com/v2.9/'.$post->id.'/attachments?format=json&access_token=' . variable_get('facebook_app_id') . '|' . variable_get('facebook_app_secret')));

            $date = format_date(strtotime($post->created_time));
            $return .= '<div class="facebook_feed">';
            $return .= '<div class="facebook_feed_date">' . $date . '</div>';

            $return .= '<a href="' . variable_get('facebook_page') . '" target="_blank">' . $message . '<br><img src="' . $jsonimg->data[0]->media->image->src. '" class="img-responsive"/> </a>';

            $return .= '</div>';
        }
        $return .= '</div></div></div>';
    }
    return $return;
}